### PR TITLE
service and disk offerings

### PR DESCRIPTION
**Pull request by poddm**
Enhanced the following resources to support the full api spec.

- cloudstack_service_offering_constrained
- cloudstack_service_offering_unconstrained
- cloudstack_service_offering_fixed

I split the service offering API up into multiple resources to make it a bit clearer of the different qos types

### CODE REVIEW

**Comment by adidiborg** [comment]
Hi @rohityadavcloud, any tentative timelines when v0.5.0 would release? Already merged features could be of a lot of use 😄

**Comment by rohityadavcloud** [comment]
Hi @adidiborg welcome to the opensource project, I hear you and I hope the community can work towards a release soon. I hope the next TF release will be sometime in coming months.

Anybody in the community can work to become a committer and PMC member, and lead release work who work in their "free" time, and it's highly encouraged that users and organisations participate and sponsor their team to work in the community. It's often seen many interested individuals and organisations come together to work on their features and sometimes releases, and often some organisations sponsor feature and maintenance work, and collaborate for testing and release work but not just limited to coding but also documentation, website, marketing and events.

Everyone is welcome to start discussions on our dev@ and users@ mailing lists, in fact your comment would be more visible on the lists unless it was only specifically for me.

**Comment by adidiborg** [comment]
> Hi @adidiborg welcome to the opensource project, I hear you and I hope the community can work towards a release soon. I hope the next TF release will be sometime in coming months.
> 
> Anybody in the community can work to become a committer and PMC member, and lead release work who work in their "free" time, and it's highly encouraged that users and organisations participate and sponsor their team to work in the community. It's often seen many interested individuals and organisations come together to work on their features and sometimes releases, and often some organisations sponsor feature and maintenance work, and collaborate for testing and release work but not just limited to coding but also documentation, website, marketing and events.
> 
> Everyone is welcome to start discussions on our dev@ and users@ mailing lists, in fact your comment would be more visible on the lists unless it was only specifically for me.

thanks for responding, I will also try to contribute whereever I can

**Comment by poddm** [comment]
Update - I'd still like to get these merged once the cloudstack SDK is updated.
- https://github.com/apache/cloudstack-terraform-provider/pull/71
- https://github.com/apache/cloudstack-terraform-provider/issues/101

**Comment by rohityadavcloud** [comment]
@poddm can you address conflicts on your PR?

**Comment by rohityadavcloud** [comment]
@poddm @fabiomatavelli I was on vacation so couldn't reply earlier.

Longer term, since you're both active contributors and if you want to main and drive releases yourselves I can propose you both as committers after which you can propose yourself to be release managers (did some write up here on the typical release process: https://cwiki.apache.org/confluence/display/CLOUDSTACK/%5BDRAFT%5D+How+to+Become+a+CloudStack+Release+Manager ) - let me know if you're interested to do that.

Looking at $dayjob pile and on-going community work, I think most of us will busy this/next month working towards the upcoming ACS 4.20 and other misc releases. We'll be available most likely in end of Q3 or in Q4 for the next ACS Terraform (Tofu) Provider releases.

Meanwhile, feel free to work on stabilising the PRs & overall main branch to be ready for release work and continue to build/use the snapshots as required. I've pinged @kiranchavala @vishesh92 who can assist with review related queries.

**Comment by poddm** [comment]
@rohityadavcloud, I'm interested.

**Comment by vishesh92** [comment]
@poddm The build is failing. Please check. 
Also, I am not sure about removing existing resource types. This can cause issues for users during an upgrade. I haven't completely checked, but the end user who will be upgrading the provider will have to migrate his existing terraform setup.

**Comment by CodeBleu** [comment]
> @poddm The build is failing. Please check. Also, I am not sure about removing existing resource types. This can cause issues for users during an upgrade. I haven't completely checked, but the end user who will be upgrading the provider will have to migrate his existing terraform setup.

@vishesh92 I don't believe the comment about "removing existing resource types" is what you think.  I understood it to mean he would remove his changes in this PR that are not related to the "service offerings" resource.

Also, @poddm if we are moving forward with your approach, can we use the new terraform plugin framework approach? #113   I think we should start moving to using that for new/updated resources.  Then eventually we can get to upgrading the rest to use the new framework.

**Comment by CodeBleu** [comment]
> > @poddm The build is failing. Please check. Also, I am not sure about removing existing resource types. This can cause issues for users during an upgrade. I haven't completely checked, but the end user who will be upgrading the provider will have to migrate his existing terraform setup.
> 
> @vishesh92 I don't believe the comment about "removing existing resource types" is what you think. I understood it to mean he would remove his changes in this PR that are not related to the "service offerings" resource.
> 
> Also, @poddm if we are moving forward with your approach, can we use the new terraform plugin framework approach? #113 I think we should start moving to using that for new/updated resources. Then eventually we can get to upgrading the rest to use the new framework.

@poddm @vishesh92 @rohityadavcloud 

Is there anything I can help with to get this merged?  I'm desperately needing to have this avail, so I can pass this on to our customers and help reduce a lot of manual management of service offerings.

**Comment by poddm** [comment]
I missed these previous messages.  Let me look at refactoring this into the new framework SDK.

**Comment by CodeBleu** [comment]
@poddm @rohityadavcloud  Since we are now in the 4th quarter, I was hoping we can start wrapping things like this up and get a new release out soon.  This one PR in particular is a significant one for me.  I really don't want to fork this and start down a different path, but at some point I might have to make that decision.

I know everyone is busy and completely appreciate all the hard work that goes into this project. I'm hoping we can get this long lived PR over the line soon and also get a release out soon.

**Comment by rohityadavcloud** [comment]
Hi @CodeBleu on the next release, we can try to start some release work in end Nov & Dec, I don't think some of us will have bandwidth until CCC (Nov 22-23). I've started this issue to track & discuss the next release, we also have a Github release milestone; https://github.com/apache/cloudstack-terraform-provider/issues/137

Usually I'm up for merging this PR but we need the merge criteria (review/update as required) to pass, for example - the Github actions acceptance tests should pass, 1-2 code review/lgtms & manual QA. Can you and/or @poddm and others help advise on that?

**Comment by rohityadavcloud** [comment]
@poddm can you review/rebase the PR & look at failing tests. Thanks.

**Comment by CodeBleu** [comment]
@poddm I see you're working on this. Thanks!!  I've been trying to test things before your recent changes, and have pulled down your recent changes too, but I believe the code is still missing the option to specify a `domain` to assign the offering to. Is that something you can add?

**Comment by CodeBleu** [comment]
This PR has been replaced with this [PR](https://github.com/apache/cloudstack-terraform-provider/pull/138)

**Pull request closed without merging**
