### PR TITLE
Fixup acceptance tests

### PR DESCRIPTION
**Pull request by vishesh92**

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
```
=== RUN   TestAccCloudStackKubernetesVersion_basic
    testing.go:568: Step 0 error: errors during apply:
        
        Error: CloudStack API error 401 (CSExceptionErrorCode: 0): unable to verify user credentials and/or request signature
        
          on /tmp/tf-test3270280120/main.tf line 2:
          (source code not available)
        
        
--- FAIL: TestAccCloudStackKubernetesVersion_basic (0.02s)
=== RUN   TestAccCloudStackKubernetesVersion_update
    testing.go:568: Step 0 error: errors during apply:
        
        Error: CloudStack API error 401 (CSExceptionErrorCode: 0): unable to verify user credentials and/or request signature
        
          on /tmp/tf-test3546500911/main.tf line 2:
          (source code not available)
        
        
--- FAIL: TestAccCloudStackKubernetesVersion_update (0.02s)
```

**Comment by vishesh92** [comment]
> ```
> === RUN   TestAccCloudStackKubernetesVersion_basic
>     testing.go:568: Step 0 error: errors during apply:
>         
>         Error: CloudStack API error 401 (CSExceptionErrorCode: 0): unable to verify user credentials and/or request signature
>         
>           on /tmp/tf-test3270280120/main.tf line 2:
>           (source code not available)
>         
>         
> --- FAIL: TestAccCloudStackKubernetesVersion_basic (0.02s)
> === RUN   TestAccCloudStackKubernetesVersion_update
>     testing.go:568: Step 0 error: errors during apply:
>         
>         Error: CloudStack API error 401 (CSExceptionErrorCode: 0): unable to verify user credentials and/or request signature
>         
>           on /tmp/tf-test3546500911/main.tf line 2:
>           (source code not available)
>         
>         
> --- FAIL: TestAccCloudStackKubernetesVersion_update (0.02s)
> ```

This is failing because CKS is disabled by default on older versions. It should work for 4.19. Other runs shouldn't have got canceled. Let me fix that.

**Review by rohityadavcloud — APPROVED** [review]
LGTM - let's wait to see the Github actions results

**Comment by vishesh92** [comment]
<details><summary>Test Results with 4.19.0</summary>
<p>

```go
 ?   	github.com/terraform-providers/terraform-provider-cloudstack	[no test files]
=== RUN   TestAccInstanceDataSource_basic
--- PASS: TestAccInstanceDataSource_basic (9.80s)
=== RUN   TestAccIPAddressDataSource_basic
--- PASS: TestAccIPAddressDataSource_basic (2.30s)
=== RUN   TestAccNetworkOfferingDataSource_basic
--- PASS: TestAccNetworkOfferingDataSource_basic (0.30s)
=== RUN   TestAccPodDataSource_basic
--- PASS: TestAccPodDataSource_basic (0.10s)
=== RUN   TestAccServiceOfferingDataSource_basic
--- PASS: TestAccServiceOfferingDataSource_basic (0.26s)
=== RUN   TestAccSshKeyPairDataSource_basic
--- PASS: TestAccSshKeyPairDataSource_basic (0.31s)
=== RUN   TestAccUserDataSource_basic
--- PASS: TestAccUserDataSource_basic (0.40s)
=== RUN   TestAccVolumeDataSource_basic
--- PASS: TestAccVolumeDataSource_basic (1.41s)
=== RUN   TestAccVPCDataSource_basic
--- PASS: TestAccVPCDataSource_basic (4.45s)
=== RUN   TestAccZoneDataSource_basic
--- PASS: TestAccZoneDataSource_basic (0.29s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccCloudStackAffinityGroup_basic
--- PASS: TestAccCloudStackAffinityGroup_basic (1.23s)
=== RUN   TestAccCloudStackAffinityGroup_import
--- PASS: TestAccCloudStackAffinityGroup_import (1.25s)
=== RUN   TestAccCloudstackAttachVolume_basic
--- PASS: TestAccCloudstackAttachVolume_basic (25.43s)
=== RUN   TestAccCloudStackAutoscaleVMProfile_basic
    testing.go:568: Step 0 error: errors during apply:
        
        Error: Error creating AutoScaleVmProfile : CloudStack API error 431 (CSExceptionErrorCode: 9999): Unable to execute API command autoscalevmprofile due to invalid value displayname=display1&networkids=net1 for parameter otherdeployparams
        
          on /tmp/tf-test884286734/main.tf line 2:
          (source code not available)
        
        
--- FAIL: TestAccCloudStackAutoscaleVMProfile_basic (0.10s)
=== RUN   TestAccCloudStackAutoscaleVMProfile_update
    testing.go:568: Step 0 error: errors during apply:
        
        Error: Error creating AutoScaleVmProfile : CloudStack API error 431 (CSExceptionErrorCode: 9999): Unable to execute API command autoscalevmprofile due to invalid value displayname=display1&networkids=net1 for parameter otherdeployparams
        
          on /tmp/tf-test3363726754/main.tf line 2:
          (source code not available)
        
        
--- FAIL: TestAccCloudStackAutoscaleVMProfile_update (0.09s)
=== RUN   TestAccCloudStackDisk_basic
--- PASS: TestAccCloudStackDisk_basic (1.34s)
=== RUN   TestAccCloudStackDisk_update
--- PASS: TestAccCloudStackDisk_update (2.50s)
=== RUN   TestAccCloudStackDisk_deviceID
--- PASS: TestAccCloudStackDisk_deviceID (24.40s)
=== RUN   TestAccCloudStackDisk_import
--- PASS: TestAccCloudStackDisk_import (1.33s)
=== RUN   TestAccCloudStackEgressFirewall_basic
--- PASS: TestAccCloudStackEgressFirewall_basic (4.55s)
=== RUN   TestAccCloudStackEgressFirewall_update
--- PASS: TestAccCloudStackEgressFirewall_update (10.99s)
=== RUN   TestAccCloudStackFirewall_basic
--- PASS: TestAccCloudStackFirewall_basic (8.87s)
=== RUN   TestAccCloudStackFirewall_update
--- PASS: TestAccCloudStackFirewall_update (14.39s)
=== RUN   TestAccCloudStackHost_basic
--- PASS: TestAccCloudStackHost_basic (15.47s)
=== RUN   TestAccCloudStackHost_fail
--- PASS: TestAccCloudStackHost_fail (10.10s)
=== RUN   TestAccCloudStackInstance_basic
--- PASS: TestAccCloudStackInstance_basic (17.96s)
=== RUN   TestAccCloudStackInstance_stopped
--- PASS: TestAccCloudStackInstance_stopped (12.80s)
=== RUN   TestAccCloudStackInstance_update
--- PASS: TestAccCloudStackInstance_update (25.39s)
=== RUN   TestAccCloudStackInstance_fixedIP
--- PASS: TestAccCloudStackInstance_fixedIP (19.85s)
=== RUN   TestAccCloudStackInstance_keyPair
--- PASS: TestAccCloudStackInstance_keyPair (19.97s)
=== RUN   TestAccCloudStackInstance_project
--- PASS: TestAccCloudStackInstance_project (20.07s)
=== RUN   TestAccCloudStackInstance_import
--- PASS: TestAccCloudStackInstance_import (17.89s)
=== RUN   TestAccCloudStackInstance_importProject
--- PASS: TestAccCloudStackInstance_importProject (20.09s)
=== RUN   TestAccCloudStackIPAddress_basic
--- PASS: TestAccCloudStackIPAddress_basic (4.66s)
=== RUN   TestAccCloudStackIPAddress_vpc
--- PASS: TestAccCloudStackIPAddress_vpc (8.59s)
=== RUN   TestAccCloudStackKubernetesVersion_basic
--- PASS: TestAccCloudStackKubernetesVersion_basic (1.40s)
=== RUN   TestAccCloudStackKubernetesVersion_update
--- PASS: TestAccCloudStackKubernetesVersion_update (1.34s)
=== RUN   TestAccCloudStackLoadBalancerRule_basic
--- PASS: TestAccCloudStackLoadBalancerRule_basic (20.27s)
=== RUN   TestAccCloudStackLoadBalancerRule_update
--- PASS: TestAccCloudStackLoadBalancerRule_update (25.74s)
=== RUN   TestAccCloudStackLoadBalancerRule_forceNew
--- PASS: TestAccCloudStackLoadBalancerRule_forceNew (23.83s)
=== RUN   TestAccCloudStackLoadBalancerRule_vpc
--- PASS: TestAccCloudStackLoadBalancerRule_vpc (20.50s)
=== RUN   TestAccCloudStackLoadBalancerRule_vpcUpdate
--- PASS: TestAccCloudStackLoadBalancerRule_vpcUpdate (30.40s)
=== RUN   TestAccCloudStackNetworkACLRule_basic
--- PASS: TestAccCloudStackNetworkACLRule_basic (14.88s)
=== RUN   TestAccCloudStackNetworkACLRule_update
--- PASS: TestAccCloudStackNetworkACLRule_update (20.47s)
=== RUN   TestAccCloudStackNetworkACL_basic
--- PASS: TestAccCloudStackNetworkACL_basic (6.51s)
=== RUN   TestAccCloudStackNetworkACL_import
--- PASS: TestAccCloudStackNetworkACL_import (8.54s)
=== RUN   TestAccCloudStackNetwork_basic
--- PASS: TestAccCloudStackNetwork_basic (1.41s)
=== RUN   TestAccCloudStackNetwork_project
--- PASS: TestAccCloudStackNetwork_project (1.45s)
=== RUN   TestAccCloudStackNetwork_vpc
--- PASS: TestAccCloudStackNetwork_vpc (7.69s)
=== RUN   TestAccCloudStackNetwork_updateACL
--- PASS: TestAccCloudStackNetwork_updateACL (42.17s)
=== RUN   TestAccCloudStackNetwork_import
--- PASS: TestAccCloudStackNetwork_import (1.36s)
=== RUN   TestAccCloudStackNetwork_importProject
--- PASS: TestAccCloudStackNetwork_importProject (1.44s)
=== RUN   TestAccCloudStackNIC_basic
--- PASS: TestAccCloudStackNIC_basic (25.84s)
=== RUN   TestAccCloudStackNIC_update
--- PASS: TestAccCloudStackNIC_update (35.45s)
=== RUN   TestAccCloudStackPortForward_basic
--- PASS: TestAccCloudStackPortForward_basic (24.29s)
=== RUN   TestAccCloudStackPortForward_update
--- PASS: TestAccCloudStackPortForward_update (23.59s)
=== RUN   TestAccCloudStackPrivateGateway_basic
--- PASS: TestAccCloudStackPrivateGateway_basic (10.73s)
=== RUN   TestAccCloudStackPrivateGateway_import
--- PASS: TestAccCloudStackPrivateGateway_import (10.72s)
=== RUN   TestAccCloudStackSecondaryIPAddress_basic
--- PASS: TestAccCloudStackSecondaryIPAddress_basic (19.11s)
=== RUN   TestAccCloudStackSecondaryIPAddress_fixedIP
--- PASS: TestAccCloudStackSecondaryIPAddress_fixedIP (22.09s)
=== RUN   TestAccCloudStackSecurityGroupRule_basic
--- PASS: TestAccCloudStackSecurityGroupRule_basic (6.50s)
=== RUN   TestAccCloudStackSecurityGroupRule_update
--- PASS: TestAccCloudStackSecurityGroupRule_update (17.06s)
=== RUN   TestAccCloudStackSecurityGroup_basic
--- PASS: TestAccCloudStackSecurityGroup_basic (0.13s)
=== RUN   TestAccCloudStackSecurityGroup_import
--- PASS: TestAccCloudStackSecurityGroup_import (0.13s)
=== RUN   TestAccCloudStackServiceOffering_basic
--- PASS: TestAccCloudStackServiceOffering_basic (0.19s)
=== RUN   TestAccCloudStackSSHKeyPair_basic
--- PASS: TestAccCloudStackSSHKeyPair_basic (0.19s)
=== RUN   TestAccCloudStackSSHKeyPair_register
--- PASS: TestAccCloudStackSSHKeyPair_register (0.13s)
=== RUN   TestAccCloudStackStaticNAT_basic
--- PASS: TestAccCloudStackStaticNAT_basic (19.24s)
=== RUN   TestAccCloudStackStaticRoute_basic
--- PASS: TestAccCloudStackStaticRoute_basic (14.87s)
=== RUN   TestAccCloudStackTemplate_basic
--- PASS: TestAccCloudStackTemplate_basic (12.95s)
=== RUN   TestAccCloudStackTemplate_update
--- PASS: TestAccCloudStackTemplate_update (11.72s)
=== RUN   TestAccCloudStackVPC_basic
--- PASS: TestAccCloudStackVPC_basic (4.38s)
=== RUN   TestAccCloudStackVPC_import
--- PASS: TestAccCloudStackVPC_import (4.43s)
=== RUN   TestAccCloudStackVPNConnection_basic
--- PASS: TestAccCloudStackVPNConnection_basic (11.95s)
=== RUN   TestAccCloudStackVPNCustomerGateway_basic
--- PASS: TestAccCloudStackVPNCustomerGateway_basic (9.76s)
=== RUN   TestAccCloudStackVPNCustomerGateway_update
--- PASS: TestAccCloudStackVPNCustomerGateway_update (13.10s)
=== RUN   TestAccCloudStackVPNCustomerGateway_import
--- PASS: TestAccCloudStackVPNCustomerGateway_import (15.79s)
=== RUN   TestAccCloudStackVPNGateway_basic
--- PASS: TestAccCloudStackVPNGateway_basic (5.51s)
=== RUN   TestAccCloudStackVPNGateway_import
--- PASS: TestAccCloudStackVPNGateway_import (5.49s)
=== RUN   TestDiffTags
--- PASS: TestDiffTags (0.00s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-cloudstack/cloudstack	863.701s
FAIL
```

</p>
</details> 

Only two tests `TestAccCloudStackAutoscaleVMProfile_basic` & `TestAccCloudStackAutoscaleVMProfile_update` are failing. This will be fixed once we upgrade the go sdk.

**Pull request merged**
